services:
  - type: web
    name: ft-transcendence
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    autoDeploy: true
