services:
  - type: web
    name: ft-transcendence-backend
    env: docker
    plan: free
    region: oregon
    branch: separate-deployment
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: render_production_jwt_secret_2024_transcendence_secure_key
    autoDeploy: true
