FROM owasp/modsecurity-crs:nginx

USER root

COPY backend/security/waf/nginx.conf /etc/nginx/templates/conf.d/default.conf.template
COPY backend/security/waf/modsecurity/config.conf /etc/nginx/templates/modsecurity.d/modsecurity.conf.template

COPY certificates /etc/nginx/certs

RUN mkdir -p /var/log/modsecurity && \
	chmod 700 /var/log/modsecurity && \
	chmod 600 /etc/nginx/certs/nginx.key